name: Monitoramento API ITUB4

on:
  schedule:
    - cron: '*/10 * * * *'   # roda a cada 10 minutos
  workflow_dispatch:         # permite rodar manualmente

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checar API
        run: |
          curl -f https://techchallenge05.onrender.com/docs || exit 1
